### ISSUE TITLE
PaperSpigot Support

### ISSUE THREAD

**Issue by elrobtossohn** [MrMicky-FR/FastBoard#14]
When i'm joining my plugin throws some exceptions, they are come only when i'm using the newest PaperSpigot (Not tested with the "normal" Spigot)

```
[15:39:11 ERROR]: Could not pass event PlayerJoinEvent to XCore v1.0
java.lang.ExceptionInInitializerError: null
        at fr.mrmicky.fastboard.FastBoard.<clinit>(FastBoard.java:158) ~[?:?]
        at xyz.shlovto.player.scoreboard.Scoreboard.setupObjective(Scoreboard.java:74) ~[?:?]
        at xyz.shlovto.core.listener.JoinListener.onJoin(JoinListener.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[spigot.jar:git-Paper-"cc063e1"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[spigot.jar:git-Paper-"cc063e1"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Paper-"cc063e1"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:299) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:308) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.network.Connection.tick(Connection.java:399) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:196) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[spigot.jar:git-Paper-"cc063e1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[spigot.jar:git-Paper-"cc063e1"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.level.EntityPlayer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[spigot.jar:git-Paper-"cc063e1"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[spigot.jar:git-Paper-"cc063e1"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at fr.mrmicky.fastboard.FastReflection.nmsClass(FastReflection.java:71) ~[?:?]
        at fr.mrmicky.fastboard.FastBoard.<clinit>(FastBoard.java:101) ~[?:?]
        ... 19 more
```

**Comment by MrMicky-FR** [comment]
What's the build number ? Tested with build #79 (latest PaperMC) and I have no issue

**Comment by elrobtossohn** [comment]
I'm tested it with a self-builded version of paperspigot

**Comment by MrMicky-FR** [comment]
Can you send me this version so I can test ? You can add me on Discord if you need (there is a Discord invite in the readme)

**Comment by elrobtossohn** [comment]
Alright, I found the error, I was stupid and took the mapped file instead of the one where everything is correct

My mistake :D
