### ISSUE TITLE
ClassCastException during initialization

### ISSUE THREAD

**Issue by martinpppx** [MrMicky-FR/FastBoard#20]
I copied everything to test how it works, and after pasting the code, I get the following message:

```
Could not pass event PlayerJoinEvent to BoardTest v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:276) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.core.board.FastBoard.<clinit>(FastBoard.java:131) ~[?:?]
	at net.core.listeners.JoinedEvent.onJoin(JoinedEvent.java:90) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	... 15 more
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.lang.String
	at java.lang.Class.cast(Class.java:3818) ~[?:?]
	at net.core.board.FastBoard.<clinit>(FastBoard.java:90) ~[?:?]
	at net.core.listeners.JoinedEvent.onJoin(JoinedEvent.java:90) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3172-Spigot-610a8c0-99561c2]
	... 15 more
```

**Comment by MrMicky-FR** [comment]
Hi, can you please send the stacktrace when using the FastBoard class without any modifications or formatting change ? Because currently looks like the lines in the stacktrace are not matching which make finding the issue much harder

**Comment by martinpppx** [comment]
I won't lie, im new to java.  How do I get the current stack trace in Java?

**Comment by MrMicky-FR** [comment]
Not saying you are lying, I think you just changed the lines number (maybe just automatic formatting of your editor), otherwise if it’s easier you can just send the current FastBoard file of your project so I can see the line numbers corresponding to the stacktrace.

**Comment by martinpppx** [comment]
I think I understand what you mean. This error is caused by the line you see in the screenshot. 
https://prnt.sc/214mpwi

**Comment by martinpppx** [comment]
Only when the playerjoinevent event is called. I mean the line 'FastBoard board = new FastBoard(player);'

**Comment by MrMicky-FR** [comment]
Thanks, I will try to see what’s cause this error when I have some time

**Comment by MasqueOu** [comment]
Exact same issue here :/

**Comment by MrMicky-FR** [comment]
Hi, unfortunately I can’t reproduce this issue :/ I tested with a simple scoreboard on Spigot 1.17.1 and the scoreboard works fine without any error. Also I can’t find any String cast in the code that could produce this issue.
Do you have any other information that could help to resolve the issue ? I’m also available on Discord (there is a link to my Discord server in the readme)

**Comment by MrMicky-FR** [comment]
This issue is caused by a bug in the Eclipse compiler, see https://bugs.openjdk.java.net/browse/JDK-8277620?attachmentSortBy=fileName and https://bugs.eclipse.org/bugs/show_bug.cgi?id=574946 (thanks @MasqueOu for helping me finding the issue)

I can’t do anything about this issue, a solution would be to configure Eclipse to use an other compiler. Otherwise you can use Maven/Gradle and/or switch to IntelliJ IDEA.
