### ISSUE TITLE
[Paper 1.20.5] Lib incompatible ?

### ISSUE THREAD

**Issue by x9nico** [MrMicky-FR/FastBoard#52]
Hello,
While trying to update my plugin to Paper 1.20.5 (build 6) with Fastboard 2.1.1, I have this error when a Player join:

```console
[12:53:51 ERROR]: Could not pass event PlayerJoinEvent to PvPBox v2.7.0 (f35bdf0-dirty)
java.lang.ExceptionInInitializerError: null
        at PvPBox-2.7.0 (f35bdf0-dirty).jar/fr.x9nico.pvpbox.utils.scoreboard.FastBoardBase.<clinit>(FastBoardBase.java:197) ~[PvPBox-2.7.0 (f35bdf0-dirty).jar:?]
        at PvPBox-2.7.0 (f35bdf0-dirty).jar/fr.x9nico.pvpbox.listeners.players.PlayerJoin.join(PlayerJoin.java:48) ~[PvPBox-2.7.0 (f35bdf0-dirty).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor20.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:git-Paper-6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.5.jar:git-Paper-6]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.5.jar:git-Paper-6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[paper-1.20.5.jar:git-Paper-6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.5.jar:git-Paper-6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at PvPBox-2.7.0 (f35bdf0-dirty).jar/fr.x9nico.pvpbox.utils.scoreboard.FastBoardBase.<clinit>(FastBoardBase.java:85) ~[PvPBox-2.7.0 (f35bdf0-dirty).jar:?]
        ... 26 more
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
        at PvPBox-2.7.0 (f35bdf0-dirty).jar/fr.x9nico.pvpbox.utils.scoreboard.FastReflection.<clinit>(FastReflection.java:46) ~[PvPBox-2.7.0 (f35bdf0-dirty).jar:?]
        at PvPBox-2.7.0 (f35bdf0-dirty).jar/fr.x9nico.pvpbox.utils.scoreboard.FastBoardBase.<clinit>(FastBoardBase.java:85) ~[PvPBox-2.7.0 (f35bdf0-dirty).jar:?]
        ... 26 more
[12:53:51 INFO]: x9nico joined the game
[12:53:51 INFO]: x9nico[/127.0.0.1:56447] logged in with entity id 1 at ([world]-293.0867609123725, 44.0, -174.4639786386085)
```

There is my code =>

onEnable method: 
```java
 Bukkit.getScheduler().runTaskTimer(this, new ScoreBoardRunnable(this), 0L, 20L);
```

PlayerJoinEvent:
```java
Player p = e.getPlayer();
        FastBoard board = new FastBoard(p) {
            public boolean hasLinesMaxLength() {
                return Via.getAPI().getPlayerVersion(getPlayer()) < ProtocolVersion.v1_13.getVersion();
            }
        };
Component sb_title = MiniMessage.miniMessage().deserialize(config.getString("sb_title"));
        board.updateTitle(sb_title);
        pvpBoxPlugin.getBoards().put(p.getUniqueId(), board);
```
(For your information, I tried with my p variable, with player uniqueid method, and I verified that I use the Fastboard class for Kiori Adventure, same error)

ScoreboardManager : 

```java
public void update(FastBoard board) {
        FileConfiguration config = pvpBoxPlugin.getConfig();
        int killStreaks = 0;
        if (pvpBoxPlugin.getKillStreak().containsKey(board.getPlayer().getUniqueId()))
            killStreaks = pvpBoxPlugin.getKillStreak().get(board.getPlayer().getUniqueId());
        Component sb_player = MiniMessage.miniMessage().deserialize(config.getString("sb_player").replace("{player}", board.getPlayer().getName()));
        Component sb_killstreaks = MiniMessage.miniMessage().deserialize(config.getString("sb_killstreaks").replace("{killStreaks}", Integer.toString(killStreaks)));
        Component sb_level = MiniMessage.miniMessage().deserialize(config.getString("sb_level").replace("{level}", String.valueOf(board.getPlayer().getLevel())));
        Component sb_ratio = MiniMessage.miniMessage().deserialize(config.getString("sb_ratio").replace("{ratio}", Double.toString(fixRatio(board.getPlayer()))));
        Component sb_deaths = MiniMessage.miniMessage().deserialize(config.getString("sb_deaths").replace("{deaths}", Integer.toString(board.getPlayer().getStatistic(Statistic.DEATHS))));
        Component sb_kills = MiniMessage.miniMessage().deserialize(config.getString("sb_kills").replace("{kills}", Integer.toString(board.getPlayer().getStatistic(Statistic.PLAYER_KILLS))));
        Component sb_ip_address = MiniMessage.miniMessage().deserialize(config.getString("sb_ip_adress"));
        board.updateLines(
                Component.empty(),
                sb_player,
                Component.empty(),
                sb_killstreaks,
                sb_level,
                sb_ratio,
                sb_deaths,
                sb_kills,
                Component.empty(),
                sb_ip_address
        );
    }

    private double fixRatio(Player player) {
        PlayerUtils playerUtils = new PlayerUtils(pvpBoxPlugin);
        return Math.round(playerUtils.getRatio(player) * 100.0D) / 100.0D;
    }
```

ScoreboardRunnable: 
```java
@Override
    public void run() {
        for (FastBoard boards : pvpBoxPlugin.getBoards().values()) {
            ScoreBoardManager scoreBoardManager = new ScoreBoardManager(pvpBoxPlugin);
            scoreBoardManager.update(boards);
        }
    }
```

Thanks :)

**Comment by syldium** [comment]
Cela m'a l'air d'être dû à la fin de relocation du package CraftBukkit sous [Paper 1.20.5](https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955).

Cette ligne n'est utilisée que pour les versions antérieures à la 1.17 :
https://github.com/MrMicky-FR/FastBoard/blob/177e5ea89888a49f050c3e3f8ff7e9dc3968146b/src/main/java/fr/mrmicky/fastboard/FastReflection.java#L46

**Comment by MrMicky-FR** [comment]
Hi, please use English for issues, as not all FastBoard users/contributors speak French :)

About the issue, @ShaneBeee on which Paper 1.20.5 build you tested in #50 ?

**Comment by ShaneBeee** [comment]
> Hi, please use English for issues, as not all FastBoard users/contributors speak French :)
> 
> About the issue, @ShaneBeee on which Paper 1.20.5 build you tested in #50 ?

I forgot to update my comment on the PR:
- I used a self built version of Paper and it works fine
- I then tried their dev build and it failed.
- It appears the dev build is using Mojang Mappings
