### ISSUE TITLE
Exception with 1.21 Support

### ISSUE THREAD

**Issue by Legundo** [MrMicky-FR/FastBoard#60]
Hello! Getting an exception whenever attempting to load this plugin in 1.21. 

Tested in purpur and paper 1.21, I'm following the shading instructions in the README. Looks similar to #52, just for 1.21. I'm just attempting to load a short scoreboard to show some static lobby information.

Exception:
```
[03:56:53 ERROR]: Could not pass event PlayerJoinEvent to EscapeFromMinecraft v1.2.0-SNAPSHOT
java.lang.ExceptionInInitializerError: null
at escape-1.2.0-SNAPSHOT.jar/com.legundo.lmgcore.scoreboards.FastBoardBase.<clinit>(FastBoardBase.java:183) ~[escape-1.2.0-SNAPSHOT.jar:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.lmgcore.managers.BoardManager.initBoard(BoardManager.java:23) ~[escape-1.2.0-SNAPSHOT.jar:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.escape.managers.ScoreboardManager.initPlayer(ScoreboardManager.java:29) ~[escape-1.2.0-SNAPSHOT.jar:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.escape.Escape.manageJoin(Escape.java:287) ~[escape-1.2.0-SNAPSHOT.jar:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.escape.EscapeListener.onPlayerJoin(EscapeListener.java:83) ~[escape-1.2.0-SNAPSHOT.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2278-b3623fa]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2278-b3623fa]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
at escape-1.2.0-SNAPSHOT.jar/com.legundo.lmgcore.scoreboards.FastBoardBase.<clinit>(FastBoardBase.java:83) ~[escape-1.2.0-SNAPSHOT.jar:?]
... 30 more
Caused by: java.lang.StringIndexOutOfBoundsException: Range [23, 22) out of bounds for length 22
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.lmgcore.scoreboards.FastReflection.<clinit>(FastReflection.java:46) ~[escape-1.2.0-SNAPSHOT.jar:?]
at escape-1.2.0-SNAPSHOT.jar/com.legundo.lmgcore.scoreboards.FastBoardBase.<clinit>(FastBoardBase.java:83) ~[escape-1.2.0-SNAPSHOT.jar:?]
... 30 more
```

Exception looks like it is being thrown from the `MethodHandles.Lookup lookup = MethodHandles.lookup();` method.

**Comment by MrMicky-FR** [comment]
You are using an old version of FastBoard (2.1.1 or lower), which is not supported on latest Minecraft version, updating to latest FastBoard will solve the issue.

The line causing the error :
https://github.com/MrMicky-FR/FastBoard/blob/v2.1.1/src/main/java/fr/mrmicky/fastboard/FastReflection.java

**Comment by Legundo** [comment]
I'll double check that no libraries are pulling in a lower version but the plugin is pulling in 2.1.3 which appears to be the latest? I've run clean on every package so it might just be import priority.

pom excerpt:
```
<dependency>
            <groupId>fr.mrmicky</groupId>
            <artifactId>fastboard</artifactId>
            <version>2.1.3</version>
            <scope>provided</scope>
        </dependency>
        ```

**Comment by MrMicky-FR** [comment]
A `provided` dependency is not compiled inside the plugin JAR, so FastBoard is included somewhere else

**Comment by Legundo** [comment]
Heya! Tried a few different things, and with or without provided we're getting the exact same issue.

**Comment by FelixTPG** [comment]
same here, not getting it to work

**Comment by MrMicky-FR** [comment]
> same here, not getting it to work

@FelixTPG Please upload the exact error rather than just saying it’s not working..
