### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SkytAsul** [MrMicky-FR/FastBoard#8]
Got this error recently:
```java
java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
    at fr.skytasul.quests.scoreboards.FastBoard.getColorCode(FastBoard.java:489) ~[?:?]
    at fr.skytasul.quests.scoreboards.FastBoard.sendScorePacket(FastBoard.java:415) ~[?:?]
    at fr.skytasul.quests.scoreboards.FastBoard.updateLines(FastBoard.java:287) ~[?:?]
 ```

**Comment by MrMicky-FR** [comment]
This is because you have too much scoreboard lines. The maximum displayed by the Minecraft client is 15 lines, so you shouldn’t have more lines
